version: '3.8'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: market
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db:/var/lib/postgresql/data
    ports:
    - "5432:5432"
volumes:
  db:
    driver: local